# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MFD_ATC260X) += atc260x-core.o atc260x-i2c.o
obj-$(CONFIG_MFD_ATC260X_AUXADC) += atc260x-auxadc.o
obj-$(CONFIG_MFD_ATC260X_POWEROFF) += atc260x-poweroff.o

