# SPDX-License-Identifier: GPL-2.0
caninos-drm-y += gfx_pipe.o gfx_drv.o de-k5.o de-k7.o gfx_de.o
obj-$(CONFIG_DRM_CANINOS) += caninos-drm.o
obj-$(CONFIG_DRM_CANINOS_HDMI) += caninos-hdmi.o
obj-$(CONFIG_DRM_CANINOS_HDMI_AUDIO) += caninos-hdmi-audio.o
