# SPDX-License-Identifier: GPL-2.0
caninosdrm-y += caninos-drm-drv.o caninos-vdc-drv.o  \
	caninos-hdmi-drv.o caninos-vdc-k5.o caninos-vdc-k7.o

caninosdrm-$(CONFIG_DRM_CANINOS_HDMI_AUDIO) += caninos-hdmi-audio.o

obj-$(CONFIG_DRM_CANINOS) += caninosdrm.o

