# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_CLK_CANINOS) += clk-caninos.o clk-pll.o \
                             clk-composite.o \
                             clk-k7.o
obj-$(CONFIG_CLK_GPU_CANINOS) += clk-gpu.o
