# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_CLK_CANINOS) += clk-caninos.o clk-mux.o clk-pll.o clk-gate.o \
                             clk-fixed.o clk-div.o clk-composite.o \
                             clk-factor.o clk-fixed-factor.o clk-k7.o
                             
